import 'package:fluent_ui/fluent_ui.dart'; import 'package:flutter_bloc/flutter_bloc.dart';
import 'dashboard_bloc.dart'; import 'system_info.dart';
class DashboardPage extends StatelessWidget { const DashboardPage({super.key});
 @override Widget build(BuildContext context)=>ScaffoldPage.scrollable(header:PageHeader(title:const Text('System overview'),commandBar:Button(onPressed:()=>context.read<DashboardBloc>().add(const DashboardRefreshRequested()),child:const Row(children:[Icon(FluentIcons.refresh),SizedBox(width:8),Text('Refresh')]))),children:[BlocBuilder<DashboardBloc,DashboardState>(builder:(_,s){if(s.status==DashboardStatus.loading&&s.info==null)return const Center(child:Padding(padding:EdgeInsets.all(48),child:ProgressRing()));if(s.info==null)return InfoBar(title:const Text('Information unavailable'),content:Text(s.error??'Waiting for data'),severity:s.status==DashboardStatus.failure?InfoBarSeverity.error:InfoBarSeverity.info);return Overview(info:s.info!,loading:s.status==DashboardStatus.loading);})]); }
class Overview extends StatelessWidget { const Overview({super.key,required this.info,required this.loading}); final SystemInfo info; final bool loading;
 @override Widget build(BuildContext context)=>Column(children:[if(loading)const Padding(padding:EdgeInsets.only(bottom:12),child:ProgressBar()),LayoutBuilder(builder:(_,c){final w=c.maxWidth>=900?(c.maxWidth-32)/3:c.maxWidth>=560?(c.maxWidth-16)/2:c.maxWidth;return Wrap(spacing:16,runSpacing:16,children:[box(w,'Computer',FluentIcons.info,[info.computer,'User: ${info.user}']),box(w,'Operating system',FluentIcons.settings,[info.os,'Version ${info.version}']),box(w,'Processor',FluentIcons.processing,[info.cpu,'${info.cores} logical processors']),usage(w,'Memory',info.ramUsage,'${info.freeRam.toStringAsFixed(1)} GB free of ${info.totalRam.toStringAsFixed(1)} GB'),usage(w,'Drive ${info.drive}',info.diskUsage,'${info.freeDisk.toStringAsFixed(1)} GB free of ${info.totalDisk.toStringAsFixed(1)} GB'),box(w,'Session',FluentIcons.clock,['Booted: ${date(info.booted)}','Updated: ${date(info.updated)}'])]);})]);
 Widget box(double w,String title,IconData icon,List<String> lines)=>SizedBox(width:w,child:Card(padding:const EdgeInsets.all(20),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Icon(icon),const SizedBox(width:10),Expanded(child:Text(title))]),const SizedBox(height:14),...lines.map((x)=>Padding(padding:const EdgeInsets.only(bottom:5),child:Text(x,maxLines:2,overflow:TextOverflow.ellipsis)))])));
 Widget usage(double w,String title,double value,String detail)=>SizedBox(width:w,child:Card(padding:const EdgeInsets.all(20),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text(title)),Text('${(value*100).round()}%')]),const SizedBox(height:14),ProgressBar(value:value*100),const SizedBox(height:10),Text(detail)])));
 String date(DateTime? x)=>x==null?'Unknown':x.toLocal().toString().split('.').first;
}
